global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: ap-northeast-2c
        access_key: AKIA6RGRQ6M5AYE3ZWUI
        secret_key: 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
        port: 9100
